"""Emit the cross-LLM table from the run data, both suites side by side.

App. K reported nine models on the suite as shipped. Sec. 5.4 shows that
suite rewarded blunt editing, so every one of those numbers is inflated
by an unknown amount and the table has to carry both columns until each
model is re-measured -- with the un-re-measured ones marked, not quietly
carried forward.

  python scripts/cross_llm_table.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from runs import resolve  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"

# display name -> (openrouter slug, vendor)
MODELS = [
    ("DeepSeek-V4-Flash", "deepseek_deepseek-v4-flash", "DeepSeek"),
    ("DeepSeek-V4-Pro", "deepseek_deepseek-v4-pro", "DeepSeek"),
    ("GPT-5.5", "openai_gpt-55", "OpenAI"),
    ("Claude-Opus-4.8", "anthropic_claude-opus-48", "Anthropic"),
    ("Gemini-3.1-pro", "google_gemini-31-pro-preview", "Google"),
    ("Qwen-3.6", "qwen_qwen36-max-preview", "Alibaba"),
]
DET_OLD, DET_NEW = 244, 245


def score(slug, suffix=""):
    # resolve() prefers the re-measured run. The completion budget was
    # not a uniform tax: the verbose models lost most and one lost
    # nothing, so a table mixing capped and uncapped rows would report a
    # vendor spread that is really a truncation spread.
    f = resolve(f"openrouter_hook_{slug}{suffix}.json")
    if not f.exists():
        return None
    return json.loads(f.read_text(encoding="utf-8-sig"))["overall_pass"]


def main():
    sys.stdout.reconfigure(encoding="utf-8")
    rows, missing = [], []
    for name, slug, vendor in MODELS:
        old, new = score(slug), score(slug, "_v07_probed")
        rows.append((name, vendor, old, new))
        if new is None:
            missing.append(name)

    print(f"{'model':<20}{'vendor':<11}{'v0.5.1':>9}{'v0.7+probe':>13}{'Δ':>8}")
    for name, vendor, old, new in rows:
        o = f"{old/385:.1%}" if old else "--"
        n = f"{new/385:.1%}" if new else "not re-measured"
        d = f"{(new-old)/385*100:+.1f}" if (old and new) else ""
        print(f"{name:<20}{vendor:<11}{o:>9}{n:>13}{d:>8}")

    done = [(n, v, o, w) for n, v, o, w in rows if w]
    if done:
        lo, hi = min(w for *_, w in done), max(w for *_, w in done)
        print(f"\nre-measured: {len(done)}/{len(rows)}   "
              f"range {lo/385:.1%}-{hi/385:.1%} "
              f"(spread {(hi-lo)/385*100:.1f} pt) "
              f"against a deterministic {DET_NEW/385:.1%}")
    if missing:
        print(f"not re-measured: {', '.join(missing)}")

    # per-run cost, read from the same run the score comes from, so the
    # price claims in the prose can be checked against the table rather
    # than against a figure someone typed once
    costs = {}
    for name, slug, _v in MODELS:
        try:
            f = resolve(f"openrouter_hook_{slug}_v07_probed.json")
            costs[name] = json.loads(
                f.read_text(encoding="utf-8-sig")).get("cost_usd")
        except Exception:
            costs[name] = None

    lines = [r"% generated by scripts/cross_llm_table.py -- do not hand-edit",
             r"\begin{tabular}{llcr}", r"\toprule",
             r"\textbf{Hook LLM} & \textbf{Vendor} & \textbf{Pass rate}"
             r" & \textbf{\$/run}\\",
             r"\midrule",
             rf"\emph{{(none)}} & --- & {DET_NEW/385*100:.1f} & 0\\",
             r"\midrule"]
    for name, vendor, old, new in rows:
        if new is None:
            continue
        c = costs.get(name)
        lines.append(f"{name} & {vendor} & \\textbf{{{new/385*100:.1f}}}"
                     f" & {('%.3f' % c) if c else '---'}\\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]

    priced = sorted((c, n) for n, c in costs.items() if c)
    if len(priced) > 1:
        lo, hi = priced[0], priced[-1]
        sc = {n: new for n, _v, _o, new in
              [(r[0], r[1], r[2], r[3]) for r in rows]}
        print("  cheapest  %-18s $%.4f  %.1f%%"
              % (lo[1], lo[0], 100 * sc[lo[1]] / 385))
        print("  priciest  %-18s $%.4f  %.1f%%"
              % (hi[1], hi[0], 100 * sc[hi[1]] / 385))
        print("  price range %.0fx" % (hi[0] / lo[0]))
    (ROOT / "paper" / "tab_cross_llm.tex").write_text(
        "\n".join(lines) + "\n", encoding="utf-8")
    print("\nwrote paper/tab_cross_llm.tex")


if __name__ == "__main__":
    main()
