"""Emit Table 2 from the v0.7 runs.

The headline table is the last thing in the paper that still carried
shipped-suite numbers, which forced the text around it to ask readers to
use the table for its pattern and take the magnitudes from elsewhere.
Every column exists at v0.7 with probe scoring, so the table is generated
from those runs and the paper quotes one set of numbers throughout.

  python scripts/main_table.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
from runs import resolve  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
P = "openrouter_hook_deepseek_deepseek-v4-flash_"

COLUMNS = [
    (r"\sysLethe{}", P + "nollm_v07_probed.json"),
    (r"\sysMem{}", P + "mem0_nollm_v07_probed.json"),
    ("LangGraph", P + "langgraph_nollm_v07_probed.json"),
    (r"\sysPalace{}", P + "mempalace_nollm_v07_probed.json"),
    (r"\sysLethe{}$+$LLM", P + "v07_probed.json"),
]
CATS = ["substring_trap", "prefix_collision", "paraphrase_supersession",
        "negation_trap", "temporal_qualifier", "shared_attribute",
        "compound_fact", "identifier_obfuscation",
        "cross_lingual_identifier", "recursive_supersession"]


def load(name):
    # resolve() prefers the re-measured run, so this table cannot
    # mix capped and uncapped numbers by omission.
    d = json.loads(resolve(name).read_text(encoding="utf-8-sig"))
    by = {k: (v["pass"], v["total"]) for k, v in d["by_category"].items()}
    return d["overall_pass"], by


def wilson(k, n, z=1.96):
    if n == 0:
        return 0.0, 0.0
    p = k / n
    d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * ((p * (1 - p) / n + z * z / (4 * n * n)) ** 0.5) / d
    return max(0.0, 100 * (c - h)), min(100.0, 100 * (c + h))


def main():
    sys.stdout.reconfigure(encoding="utf-8")
    cols = [(label, *load(f)) for label, f in COLUMNS]

    lines = [r"% generated by scripts/main_table.py -- do not hand-edit",
             r"\begin{tabular}{lccccc}", r"\toprule",
             r"\textbf{Attack category} & "
             + " & ".join(rf"\textbf{{{c[0]}}}" for c in cols) + r"\\",
             r"\midrule"]

    # compound_fact is a primitive-existence flag rather than a forgetting
    # score, so it sits below the total instead of inside it.
    PRIMITIVE = "compound_fact"
    FORGET = [c for c in CATS if c != PRIMITIVE]

    def row(cat):
        cells = []
        for _, _, by in cols:
            k, n = by.get(cat, (0, 0))
            cells.append(f"{k}/{n} ({round(100 * k / n) if n else 0})")
        name = cat.replace("_", r"\_")
        n = cols[0][2].get(cat, (0, 0))[1]
        return rf"{name} (n={n}) & " + " & ".join(cells) + r"\\"

    for cat in FORGET:
        lines.append(row(cat))

    denom = sum(cols[0][2].get(c, (0, 0))[1] for c in FORGET)
    subtotals = []
    for _, _, by in cols:
        subtotals.append(sum(by.get(c, (0, 0))[0] for c in FORGET))

    # Coverage: a store that cannot express an operation through any
    # composition of its API contributes N/A, not a failure. Strict counts
    # those cases against it, evaluable drops them; both are reported so a
    # reader can see which one a claim rests on.
    import json as _json
    cov = _json.loads((ROOT / "data" / "coverage.json")
                      .read_text(encoding="utf-8"))["na"]
    NAMES = ["Lethe", "Mem0", "LangGraph", "MemPalace", "Lethe+LLM"]
    na_forget = []
    for nm in NAMES:
        by = cov.get(nm, {}).get("by_category", {})
        na_forget.append(sum(v for c, v in by.items() if c != PRIMITIVE))

    lines.append(r"\midrule")
    # The bold row is the whole suite, strict, because Section 4 argues a
    # store that cannot express a deletion has not forgotten anything and
    # dropping those cases would reward it for the gap. The forgetting
    # frame is the row beneath, labelled, because compound_fact asks
    # whether a partial-edit primitive exists rather than whether a store
    # can be commanded to forget -- and Section 5 states the placement
    # claim on that row, so granting the objection costs nothing.
    prim_n = cols[0][2].get(PRIMITIVE, (0, 0))[1]
    all_n = denom + prim_n
    all_pass = [sub + by.get(PRIMITIVE, (0, 0))[0]
                for sub, (_, _, by) in zip(subtotals, cols)]
    lines.append(r"\textbf{All %d cases} (strict) & " % all_n + " & ".join(
        rf"\textbf{{{v}/{all_n} ({100 * v / all_n:.1f})}}" for v in all_pass)
        + r"\\")
    # Directly under the row it bounds. It once sat two rows away and was
    # computed on a different denominator from the one it was labelled
    # for, so four of five intervals excluded their own mean.
    lines.append(r"\quad 95\,\% Wilson CI & " + " & ".join(
        "[%.1f, %.1f]" % wilson(v, all_n) for v in all_pass) + r"\\")
    lines.append(r"\quad the %d that measure forgetting & " % denom
                 + " & ".join(
        rf"{t}/{denom} ({100 * t / denom:.1f})" for t in subtotals) + r"\\")
    # No evaluable row here. It used to print the numerator over
    # denom - na_forget, i.e. the 345 frame, while sitting under a strict
    # row on 385 -- so a store with full coverage appeared to have a 7.4 pt
    # coverage gap it does not have. On the basis it is actually defined
    # over, every system in this table has na = 0 (data/coverage.json) and
    # the row would restate the strict row cell for cell. The distinction
    # earns its place in the ecosystem tables, where it is not degenerate.
    assert all(na == 0 for na in na_forget[:3] + na_forget[4:]), (
        "a primary system now has N/A cases; Table 1 needs its evaluable "
        "row back: %r" % (na_forget,))
    # The count is recoverable from the evaluable denominator, and the
    # main text is a few lines from the page limit.
    lines.append(r"\midrule")
    lines.append(r"\multicolumn{" + str(len(cols) + 1)
                 + r"}{l}{\emph{primitive-existence diagnostic: inside the "
                   r"%d-case total, outside the %d-case forgetting row}}\\" % (all_n, denom))
    lines.append(r"\quad " + row(PRIMITIVE))
    lines += [r"\bottomrule", r"\end{tabular}"]

    (ROOT / "paper" / "tab_adv.tex").write_text("\n".join(lines) + "\n",
                                                encoding="utf-8")

    print(f"{'category':<28}" + "".join(f"{c[0][:11]:>13}" for c in cols))
    for cat in CATS:
        row = f"{cat:<28}"
        for _, _, by in cols:
            k, n = by.get(cat, (0, 0))
            row += f"{k:>7}/{n:<5}"
        print(row)
    print(f"{'OVERALL':<28}" + "".join(f"{c[1]:>7}/385  " for c in cols))
    print("\nwrote paper/tab_adv.tex")


if __name__ == "__main__":
    main()
